=== teamchef/OpenWebsoccer/openwebsoccer/modules/openwebsoccer.dtd
<!---
*
* This file is part of OpenWebSoccer-Sim.
*
* OpenWebSoccer-Sim is free software: you can redistribute it
* and/or modify it under the terms of the
* GNU Lesser General Public License
* as published by the Free Software Foundation,either version 3 of
* the License,or any later version.
*
* OpenWebSoccer-Sim is distributed in the hope that it will be
* useful,but WITHOUT ANY WARRANTY; without even the implied
* warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU Lesser General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with OpenWebSoccer-Sim.
* If not,see <http://www.gnu.org/licenses/>.
*
* Author: Ingo Hofmann
* Base Version: OpenWebSoccer-Sim 5.2.4-Snapshot vom 21. Juni 2015
*
* This Version called "OpenWebsoccer" is a advanced modification
* by Rolf Joseph / ErdemCan 2015 - 2016
*
* For comparison of the code look at the original at
* https://github.com/ihofmann/open-websoccer
-->
<!ELEMENT module (admin?|settings?|pages?|dependencies?|blocks?|actions?|plugins?|messages?)*>
	<!ATTLIST module version CDATA #REQUIRED>
	<!ATTLIST message id CDATA #REQUIRED>
<!ELEMENT messages (message+)>
<!ELEMENT message (#PCDATA|strong|b|i|a|em|p|ul|br)*>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT em (#PCDATA)>
<!ELEMENT p (#PCDATA|strong|b|i|a|em|p|ul)*>
<!ELEMENT a (#PCDATA)>
<!ELEMENT ul (li+)>
<!ELEMENT li (#PCDATA)>
<!ELEMENT br (#PCDATA)>
	<!ATTLIST a href CDATA #IMPLIED>
	<!ATTLIST a target CDATA #IMPLIED>
	<!ATTLIST a class CDATA #IMPLIED>
<!ELEMENT dependencies (dependency+)>
<!ELEMENT dependency EMPTY>
	<!ATTLIST dependency module CDATA #REQUIRED>
	<!ATTLIST dependency version CDATA #REQUIRED>
<!ELEMENT admin (adminpage+)>
<!ELEMENT adminpage (entity?)>
	<!ATTLIST adminpage id CDATA #REQUIRED>
	<!ATTLIST adminpage navcategory CDATA #REQUIRED>
	<!ATTLIST adminpage entity CDATA #IMPLIED>
	<!ATTLIST adminpage permissionrole (r_admin|r_daten|r_adminuser|r_news|r_spiele|r_user) #IMPLIED>
	<!ATTLIST adminpage filename CDATA #IMPLIED>
<!ELEMENT entity (overview,editform?)>
	<!ATTLIST entity dbtable CDATA #REQUIRED>
<!ELEMENT overview (column+,join*)>
	<!ATTLIST overview add (true|false) "true">
	<!ATTLIST overview edit (true|false) "false">
	<!ATTLIST overview delete (true|false) "false">
	<!ATTLIST overview logging (true|false) "false">
	<!ATTLIST overview loggingcolumns CDATA #IMPLIED>
<!ELEMENT column EMPTY>
	<!ATTLIST column id CDATA #REQUIRED>
	<!ATTLIST column filter (true|false) "false">
	<!ATTLIST column sort (true|false) "false">
	<!ATTLIST column type (text|number|email|boolean|select|timestamp|percent|fk) #REQUIRED>
	<!ATTLIST column field CDATA #REQUIRED>
	<!ATTLIST column selection CDATA #IMPLIED>
	<!ATTLIST column converter CDATA #IMPLIED>
	<!ATTLIST column hidden (true|false) "false">
<!ELEMENT join EMPTY>
	<!ATTLIST join type (LEFT|INNER|RIGHT) #REQUIRED>
	<!ATTLIST join jointable CDATA #REQUIRED>
	<!ATTLIST join joincondition CDATA #REQUIRED>
<!ELEMENT editform (field+)>
<!ELEMENT field EMPTY>
	<!ATTLIST field id CDATA #REQUIRED>
	<!ATTLIST field required (true|false) "false">
	<!ATTLIST field editonly (true|false) "false">
	<!ATTLIST field type (text|number|email|boolean|password|url|select|textarea|file|timestamp|color|date|percent|foreign_key) #REQUIRED>
	<!ATTLIST field converter CDATA #IMPLIED>
	<!ATTLIST field validator CDATA #IMPLIED>
	<!ATTLIST field entity CDATA #IMPLIED>
	<!ATTLIST field jointable CDATA #IMPLIED>
	<!ATTLIST field cascade CDATA #FIXED "delete">
	<!ATTLIST field labelcolumns CDATA #IMPLIED>
	<!ATTLIST field selection CDATA #IMPLIED>
	<!ATTLIST field roles CDATA #IMPLIED>
	<!ATTLIST field readonly (true|false) "false">
	<!ATTLIST field default CDATA #IMPLIED>
<!ELEMENT settings (setting+)>
<!ELEMENT setting EMPTY>
	<!ATTLIST setting id CDATA #REQUIRED>
	<!ATTLIST setting type (text|number|email|boolean|password|url|select|textarea|timestamp|foreign_key|tags) #REQUIRED>
	<!ATTLIST setting category CDATA #IMPLIED>
	<!ATTLIST setting default CDATA #IMPLIED>
	<!ATTLIST setting selection CDATA #IMPLIED>
<!ELEMENT pages (page+)>
<!ELEMENT page (page*,script*,css*)>
	<!ATTLIST page id CDATA #REQUIRED>
	<!ATTLIST page template CDATA #REQUIRED>
	<!ATTLIST page role CDATA #REQUIRED>
	<!ATTLIST page model CDATA #IMPLIED>
	<!ATTLIST page parentItem CDATA #IMPLIED>
	<!ATTLIST page navweight CDATA #IMPLIED>
	<!ATTLIST page navitem (true|false) "false">
	<!ATTLIST page ConfigSet CDATA #IMPLIED>
	<!ATTLIST page premiumBalanceMin CDATA #IMPLIED>
<!ELEMENT script EMPTY>
	<!ATTLIST script file CDATA #REQUIRED>
	<!ATTLIST script debugonly (true|false) "false">
	<!ATTLIST script productiononly (true|false) "false">
<!ELEMENT css EMPTY>
	<!ATTLIST css file CDATA #REQUIRED>
	<!ATTLIST css debugonly (true|false) "false">
	<!ATTLIST css productiononly (true|false) "false">
<!ELEMENT blocks (block+)>
<!ELEMENT block EMPTY>
	<!ATTLIST block id CDATA #REQUIRED>
	<!ATTLIST block template CDATA #REQUIRED>
	<!ATTLIST block role CDATA #REQUIRED>
	<!ATTLIST block model CDATA #IMPLIED>
	<!ATTLIST block includepages CDATA #IMPLIED>
	<!ATTLIST block area (sidebar|content_top|content_bottom|custom) #IMPLIED>
	<!ATTLIST block weight CDATA #IMPLIED>
	<!ATTLIST block excludepages CDATA #IMPLIED>
	<!ATTLIST block premiumBalanceMin CDATA #IMPLIED>
<!ELEMENT actions (action+)>
<!ELEMENT action (param*)>
	<!ATTLIST action id CDATA #REQUIRED>
	<!ATTLIST action role CDATA #REQUIRED>
	<!ATTLIST action controller CDATA #REQUIRED>
	<!ATTLIST action premiumBalanceMin CDATA #IMPLIED>
	<!ATTLIST action log (true|false) "false">
<!ELEMENT param EMPTY>
	<!ATTLIST param id CDATA #REQUIRED>
	<!ATTLIST param type (text|number|email|boolean|password|date|url|percent) #REQUIRED>
	<!ATTLIST param required (true|false) "false">
	<!ATTLIST param min CDATA #IMPLIED>
	<!ATTLIST param max CDATA #IMPLIED>
	<!ATTLIST param validator CDATA #IMPLIED>
<!ELEMENT plugins (eventlistener+)>
<!ELEMENT eventlistener EMPTY>
	<!ATTLIST eventlistener event CDATA #REQUIRED>
	<!ATTLIST eventlistener class CDATA #REQUIRED>
	<!ATTLIST eventlistener method CDATA #REQUIRED>

=== teamchef/OpenWebsoccer/addons_old/premiumpaypal/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../openwebsoccer.dtd">

<!---
    * This file is part of OpenWebSoccer-Sim.
    *
    * OpenWebSoccer-Sim is free software: you can redistribute it
    * and/or modify it under the terms of the
    * GNU Lesser General Public License
    * as published by the Free Software Foundation, either version 3 of
    * the License, or any later version.
    *
    * OpenWebSoccer-Sim is distributed in the hope that it will be
    * useful, but WITHOUT ANY WARRANTY; without even the implied
    * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    * See the GNU Lesser General Public License for more details.
    *
    * You should have received a copy of the GNU Lesser General Public
    * License along with OpenWebSoccer-Sim.
    * If not, see
    <http://www.gnu.org/licenses/>.
-->

<module version="OpenWebsoccer">
    <settings>
        <setting id="paypal_enabled" category="premium" type="boolean" default="false"/>
        <setting id="paypal_receiver_email" category="premium" type="email" default=""/>
        <setting id="paypal_host" category="premium" type="text" default="www.paypal.com"/>
        <setting id="paypal_url" category="premium" type="url" default="ssl://www.paypal.com"/>
        <setting id="paypal_buttonhtml" category="premium" type="textarea" default=""/>
    </settings>

    <actions>
        <action id="paypal-notify" controller="PaypalPaymentNotificationController" role="guest,user">
            <param id="receiver_email" type="email" required="true"/>
            <param id="mc_gross" type="text" required="true"/>
            <param id="settle_amount" type="text" required="false"/>
            <param id="custom" type="number" required="true"/>
            <param id="payment_status" type="text" required="true"/>
        </action>
    </actions>

    <blocks>
        <block
                id="paypalpaymentlink"
                template="paypalpaymentlink"
                includepages="premium-feature-requested"
                area="content_bottom"
                weight="1"
                role="user"
                model="PaypalLinkModel"/>
    </blocks>
</module>

=== teamchef/OpenWebsoccer/openwebsoccer/modules/clubslogo/messages_de.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE module SYSTEM "../openwebsoccer.dtd">
<!---
*
* This file is part of OpenWebSoccer-Sim.
*
* OpenWebSoccer-Sim is free software: you can redistribute it
* and/or modify it under the terms of the
* GNU Lesser General Public License
* as published by the Free Software Foundation, either version 3 of
* the License, or any later version.
*
* OpenWebSoccer-Sim is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied
* warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU Lesser General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with OpenWebSoccer-Sim.
* If not, see <http://www.gnu.org/licenses/>.
*
* Author: Ingo Hofmann
* Base Version: OpenWebSoccer-Sim 5.2.3 - 2015
*
* This Version called "OpenWebsoccer" is a advanced modification
* by Rolf Joseph / ErdemCan 2015 - 2016
*
* For comparison of the code look at the original at
* https://github.com/ihofmann/open-websoccer
-->
<module version="OpenWebsoccer">
	<messages>
		<message id="upload-clublogo_navlabel">Neues Vereinslogo hochladen</message>
		<message id="upload-clublogo_intro">Sie können hier ein PNG- oder JPEG-Bild hochladen. Es muss <strong>rechteckig</strong> sein mit einer Mindestbreite von <strong>120 Pixel</strong> und einer maximalen Dateigrösse von <strong>%d KBytes</strong>.</message>
		<message id="upload-clublogo_success">Das neue Vereinslogo wurde erfolgreich hochgeladen!</message>
		<message id="activitylog_upload-club-picture">%s hat ein neues Vereinslogo hochgeladen.</message>
	</messages>
</module>

=== teamchef/OpenWebsoccer/addons_old/facebook/messages_de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../openwebsoccer.dtd">

<!---
    * This file is part of OpenWebSoccer-Sim.
    *
    * OpenWebSoccer-Sim is free software: you can redistribute it
    * and/or modify it under the terms of the
    * GNU Lesser General Public License
    * as published by the Free Software Foundation, either version 3 of
    * the License, or any later version.
    *
    * OpenWebSoccer-Sim is distributed in the hope that it will be
    * useful, but WITHOUT ANY WARRANTY; without even the implied
    * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    * See the GNU Lesser General Public License for more details.
    *
    * You should have received a copy of the GNU Lesser General Public
    * License along with OpenWebSoccer-Sim.
    * If not, see
    <http://www.gnu.org/licenses/>.
-->

<module version="OpenWebsoccer">
    <messages>
        <message id="facebooklogin_failure">Die Anmeldung über Facebook wurde abgebrochen.</message>
        <message id="facebooklogin_success">Erfolgreich über Facebook angemeldet!</message>
        <message id="facebook_login_button">Über Facebook anmelden</message>
        <message id="facebooklogout_failure">Sie konnten nicht abgemeldet werden! Probieren Sie es noch einmal.
        </message>
        <message id="facebooklogout_success">Erfolgreich abgemeldet!</message>
        <message id="facebooklogout_success_details">Bitte beachten Sie, dass Sie aus Sicherheitsgründen auch aus
            Facebook abgemeldet wurden.
        </message>
    </messages>
</module>
