=== teamchef/OpenWebsoccer/openwebsoccer/modules/openwebsoccer.dtd
<!---
*
* This file is part of OpenWebSoccer-Sim.
*
* OpenWebSoccer-Sim is free software: you can redistribute it
* and/or modify it under the terms of the
* GNU Lesser General Public License
* as published by the Free Software Foundation,either version 3 of
* the License,or any later version.
*
* OpenWebSoccer-Sim is distributed in the hope that it will be
* useful,but WITHOUT ANY WARRANTY; without even the implied
* warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU Lesser General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with OpenWebSoccer-Sim.
* If not,see <http://www.gnu.org/licenses/>.
*
* Author: Ingo Hofmann
* Base Version: OpenWebSoccer-Sim 5.2.4-Snapshot vom 21. Juni 2015
*
* This Version called "OpenWebsoccer" is a advanced modification
* by Rolf Joseph / ErdemCan 2015 - 2016
*
* For comparison of the code look at the original at
* https://github.com/ihofmann/open-websoccer
-->
<!ELEMENT module (admin?|settings?|pages?|dependencies?|blocks?|actions?|plugins?|messages?)*>
	<!ATTLIST module version CDATA #REQUIRED>
	<!ATTLIST message id CDATA #REQUIRED>
<!ELEMENT messages (message+)>
<!ELEMENT message (#PCDATA|strong|b|i|a|em|p|ul|br)*>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT em (#PCDATA)>
<!ELEMENT p (#PCDATA|strong|b|i|a|em|p|ul)*>
<!ELEMENT a (#PCDATA)>
<!ELEMENT ul (li+)>
<!ELEMENT li (#PCDATA)>
<!ELEMENT br (#PCDATA)>
	<!ATTLIST a href CDATA #IMPLIED>
	<!ATTLIST a target CDATA #IMPLIED>
	<!ATTLIST a class CDATA #IMPLIED>
<!ELEMENT dependencies (dependency+)>
<!ELEMENT dependency EMPTY>
	<!ATTLIST dependency module CDATA #REQUIRED>
	<!ATTLIST dependency version CDATA #REQUIRED>
<!ELEMENT admin (adminpage+)>
<!ELEMENT adminpage (entity?)>
	<!ATTLIST adminpage id CDATA #REQUIRED>
	<!ATTLIST adminpage navcategory CDATA #REQUIRED>
	<!ATTLIST adminpage entity CDATA #IMPLIED>
	<!ATTLIST adminpage permissionrole (r_admin|r_daten|r_adminuser|r_news|r_spiele|r_user) #IMPLIED>
	<!ATTLIST adminpage filename CDATA #IMPLIED>
<!ELEMENT entity (overview,editform?)>
	<!ATTLIST entity dbtable CDATA #REQUIRED>
<!ELEMENT overview (column+,join*)>
	<!ATTLIST overview add (true|false) "true">
	<!ATTLIST overview edit (true|false) "false">
	<!ATTLIST overview delete (true|false) "false">
	<!ATTLIST overview logging (true|false) "false">
	<!ATTLIST overview loggingcolumns CDATA #IMPLIED>
<!ELEMENT column EMPTY>
	<!ATTLIST column id CDATA #REQUIRED>
	<!ATTLIST column filter (true|false) "false">
	<!ATTLIST column sort (true|false) "false">
	<!ATTLIST column type (text|number|email|boolean|select|timestamp|percent|fk) #REQUIRED>
	<!ATTLIST column field CDATA #REQUIRED>
	<!ATTLIST column selection CDATA #IMPLIED>
	<!ATTLIST column converter CDATA #IMPLIED>
	<!ATTLIST column hidden (true|false) "false">
<!ELEMENT join EMPTY>
	<!ATTLIST join type (LEFT|INNER|RIGHT) #REQUIRED>
	<!ATTLIST join jointable CDATA #REQUIRED>
	<!ATTLIST join joincondition CDATA #REQUIRED>
<!ELEMENT editform (field+)>
<!ELEMENT field EMPTY>
	<!ATTLIST field id CDATA #REQUIRED>
	<!ATTLIST field required (true|false) "false">
	<!ATTLIST field editonly (true|false) "false">
	<!ATTLIST field type (text|number|email|boolean|password|url|select|textarea|file|timestamp|color|date|percent|foreign_key) #REQUIRED>
	<!ATTLIST field converter CDATA #IMPLIED>
	<!ATTLIST field validator CDATA #IMPLIED>
	<!ATTLIST field entity CDATA #IMPLIED>
	<!ATTLIST field jointable CDATA #IMPLIED>
	<!ATTLIST field cascade CDATA #FIXED "delete">
	<!ATTLIST field labelcolumns CDATA #IMPLIED>
	<!ATTLIST field selection CDATA #IMPLIED>
	<!ATTLIST field roles CDATA #IMPLIED>
	<!ATTLIST field readonly (true|false) "false">
	<!ATTLIST field default CDATA #IMPLIED>
<!ELEMENT settings (setting+)>
<!ELEMENT setting EMPTY>
	<!ATTLIST setting id CDATA #REQUIRED>
	<!ATTLIST setting type (text|number|email|boolean|password|url|select|textarea|timestamp|foreign_key|tags) #REQUIRED>
	<!ATTLIST setting category CDATA #IMPLIED>
	<!ATTLIST setting default CDATA #IMPLIED>
	<!ATTLIST setting selection CDATA #IMPLIED>
<!ELEMENT pages (page+)>
<!ELEMENT page (page*,script*,css*)>
	<!ATTLIST page id CDATA #REQUIRED>
	<!ATTLIST page template CDATA #REQUIRED>
	<!ATTLIST page role CDATA #REQUIRED>
	<!ATTLIST page model CDATA #IMPLIED>
	<!ATTLIST page parentItem CDATA #IMPLIED>
	<!ATTLIST page navweight CDATA #IMPLIED>
	<!ATTLIST page navitem (true|false) "false">
	<!ATTLIST page ConfigSet CDATA #IMPLIED>
	<!ATTLIST page premiumBalanceMin CDATA #IMPLIED>
<!ELEMENT script EMPTY>
	<!ATTLIST script file CDATA #REQUIRED>
	<!ATTLIST script debugonly (true|false) "false">
	<!ATTLIST script productiononly (true|false) "false">
<!ELEMENT css EMPTY>
	<!ATTLIST css file CDATA #REQUIRED>
	<!ATTLIST css debugonly (true|false) "false">
	<!ATTLIST css productiononly (true|false) "false">
<!ELEMENT blocks (block+)>
<!ELEMENT block EMPTY>
	<!ATTLIST block id CDATA #REQUIRED>
	<!ATTLIST block template CDATA #REQUIRED>
	<!ATTLIST block role CDATA #REQUIRED>
	<!ATTLIST block model CDATA #IMPLIED>
	<!ATTLIST block includepages CDATA #IMPLIED>
	<!ATTLIST block area (sidebar|content_top|content_bottom|custom) #IMPLIED>
	<!ATTLIST block weight CDATA #IMPLIED>
	<!ATTLIST block excludepages CDATA #IMPLIED>
	<!ATTLIST block premiumBalanceMin CDATA #IMPLIED>
<!ELEMENT actions (action+)>
<!ELEMENT action (param*)>
	<!ATTLIST action id CDATA #REQUIRED>
	<!ATTLIST action role CDATA #REQUIRED>
	<!ATTLIST action controller CDATA #REQUIRED>
	<!ATTLIST action premiumBalanceMin CDATA #IMPLIED>
	<!ATTLIST action log (true|false) "false">
<!ELEMENT param EMPTY>
	<!ATTLIST param id CDATA #REQUIRED>
	<!ATTLIST param type (text|number|email|boolean|password|date|url|percent) #REQUIRED>
	<!ATTLIST param required (true|false) "false">
	<!ATTLIST param min CDATA #IMPLIED>
	<!ATTLIST param max CDATA #IMPLIED>
	<!ATTLIST param validator CDATA #IMPLIED>
<!ELEMENT plugins (eventlistener+)>
<!ELEMENT eventlistener EMPTY>
	<!ATTLIST eventlistener event CDATA #REQUIRED>
	<!ATTLIST eventlistener class CDATA #REQUIRED>
	<!ATTLIST eventlistener method CDATA #REQUIRED>

=== teamchef/OpenWebsoccer/addons_old/premiumsofortcom/messages_de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../openwebsoccer.dtd">

<!---
    * This file is part of OpenWebSoccer-Sim.
    *
    * OpenWebSoccer-Sim is free software: you can redistribute it
    * and/or modify it under the terms of the
    * GNU Lesser General Public License
    * as published by the Free Software Foundation, either version 3 of
    * the License, or any later version.
    *
    * OpenWebSoccer-Sim is distributed in the hope that it will be
    * useful, but WITHOUT ANY WARRANTY; without even the implied
    * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    * See the GNU Lesser General Public License for more details.
    *
    * You should have received a copy of the GNU Lesser General Public
    * License along with OpenWebSoccer-Sim.
    * If not, see
    <http://www.gnu.org/licenses/>.
-->

<module version="OpenWebsoccer">
    <messages>
        <message id="actionsubject_sofortcom-notify">Zahlung über Sofort.com</message>
        <message id="sofortcompayment_link_title">Zahlen über Sofort.com</message>
        <message id="sofortcompayment_link_intro">Bezahlen Sie einfach mit Ihren Online-Banking-Daten über den Anbieter <a href="https://www.sofort.com" target="_blank">Sofort.com</a>. Sie müssen sich dazu weder bei dem Anbieter registrieren, noch benötigen Sie eine Kreditkarte.</message>
        <message id="sofortcompayment_label_amount">Betrag</message>
        <message id="sofortcompayment_label_submit">Auf Sofort.com kaufen</message>
    </messages>
</module>

=== teamchef/OpenWebsoccer/addons_old/premiumsofortcom/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../openwebsoccer.dtd">

<!---
    * This file is part of OpenWebSoccer-Sim.
    *
    * OpenWebSoccer-Sim is free software: you can redistribute it
    * and/or modify it under the terms of the
    * GNU Lesser General Public License
    * as published by the Free Software Foundation, either version 3 of
    * the License, or any later version.
    *
    * OpenWebSoccer-Sim is distributed in the hope that it will be
    * useful, but WITHOUT ANY WARRANTY; without even the implied
    * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    * See the GNU Lesser General Public License for more details.
    *
    * You should have received a copy of the GNU Lesser General Public
    * License along with OpenWebSoccer-Sim.
    * If not, see
    <http://www.gnu.org/licenses/>.
-->

<module version="OpenWebsoccer">
    <settings>
        <setting id="sofortcom_enabled" category="premium" type="boolean" default="false"/>
        <setting id="sofortcom_configkey" category="premium" type="text" default=""/>
    </settings>

    <actions>
        <action id="sofortcom-notify" controller="SofortComPaymentNotificationController" role="guest,user">
            <param id="u" type="number" required="true"/>
        </action>

        <action id="sofortcom-redirect" controller="SofortComRedirectController" role="user">
            <param id="amount" type="number" required="true" min="1"/>
        </action>
    </actions>

    <blocks>
        <block
                id="sofortcompaymentlink"
                template="sofortcompaymentlink"
                includepages="premium-feature-requested"
                area="content_bottom"
                weight="1"
                role="user"/>
    </blocks>
</module>

=== teamchef/OpenWebsoccer/addons_old/premiumpaypal/adminmessages_de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../openwebsoccer.dtd">

<!---
    * This file is part of OpenWebSoccer-Sim.
    *
    * OpenWebSoccer-Sim is free software: you can redistribute it
    * and/or modify it under the terms of the
    * GNU Lesser General Public License
    * as published by the Free Software Foundation, either version 3 of
    * the License, or any later version.
    *
    * OpenWebSoccer-Sim is distributed in the hope that it will be
    * useful, but WITHOUT ANY WARRANTY; without even the implied
    * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    * See the GNU Lesser General Public License for more details.
    *
    * You should have received a copy of the GNU Lesser General Public
    * License along with OpenWebSoccer-Sim.
    * If not, see
    <http://www.gnu.org/licenses/>.
-->

<module version="OpenWebsoccer">
    <messages>
        <message id="settings_label_paypal_enabled">Premiumguthaben durch Zahlungen über PayPal erwerben.</message>
        <message id="settings_label_paypal_receiver_email">PayPal: Kontoname (E-Mail)</message>
        <message id="settings_label_paypal_receiver_email_help">Empfänger-E-Mail. Muss die Adresse sein, die auf PayPal hinterlegt ist.</message>
        <message id="settings_label_paypal_host">PayPal: Host</message>
        <message id="settings_label_paypal_host_help">Für gewöhnlich<em>www.paypal.com</em>. Für Testbetrieb: <em>www.sandbox.paypal.com</em></message>
        <message id="settings_label_paypal_url">URL zu PayPal</message>
        <message id="settings_label_paypal_url_help">Interner URL zur Zahlungsüberprüfung. Für gewöhnlich<em> ssl://www.paypal.com</em>. Für Testbetrieb:<em>ssl://www.sandbox.paypal.com</em>.</message>
        <message id="settings_label_paypal_buttonhtml">PayPal: Buttoncode (HTML)</message>
        <message id="settings_label_paypal_buttonhtml_help"><strong>Unbearbeiteter</strong> HTML-Code des Buttons, der über das Händlerportal auf PayPal von Ihnen erzeugt wurde. Der Button muss die oben konfigurierten Einzahlungsoptionen in der angegebenen Währung beinhalten. Lesen Sie dazu auch die Produktdokumentation.</message>
    </messages>
</module>

=== teamchef/OpenWebsoccer/openwebsoccer/modules/frontend/adminmessages_de.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE module SYSTEM "../openwebsoccer.dtd">
<!---
*
* This file is part of OpenWebSoccer-Sim.
*
* OpenWebSoccer-Sim is free software: you can redistribute it
* and/or modify it under the terms of the
* GNU Lesser General Public License
* as published by the Free Software Foundation, either version 3 of
* the License, or any later version.
*
* OpenWebSoccer-Sim is distributed in the hope that it will be
* useful, but WITHOUT ANY WARRANTY; without even the implied
* warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU Lesser General Public License for more details.
*
* You should have received a copy of the GNU Lesser General Public
* License along with OpenWebSoccer-Sim.
* If not, see <http://www.gnu.org/licenses/>.
*
* Author: Ingo Hofmann
* Base Version: OpenWebSoccer-Sim 5.2.4-Snapshot vom 21. Juni 2015
*
* This Version called "OpenWebsoccer" is a advanced modification
* by Rolf Joseph / ErdemCan 2015 - 2016
*
* For comparison of the code look at the original at
* https://github.com/ihofmann/open-websoccer
-->
<module version="OpenWebsoccer">
	<messages>
		<message id="settings_tab_frontend">Frontend</message>
		<message id="imprint_navlabel">Impressum</message>
		<message id="imprint_label_content">Seiteninhalt</message>
		<message id="imprint_label_content_help">HTML ist erlaubt. Zeilenumbrüche werden automatisch umgewandelt.</message>
		<message id="imprint_introduction">In der Regel ist es aus rechtlichen Gründen erforderlich, den verantwortlichen Webseitenbetreiber auf der Webseite öffentlich anzugeben. Tragen Sie dazu die Kontaktdaten des Seitenbetreibers unten ein. Sie erscheinen auf der Webseite unter "Impressum".</message>
		<message id="imprint_validationerror_content">Es muss ein Inhalt angegeben werden.</message>
		<message id="settings_label_head_code">HTML-Code für den &lt;head&gt;-Bereich</message>
	</messages>
</module>

=== teamchef/OpenWebsoccer/addons_old/googleplus/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../openwebsoccer.dtd">

<!---
    * This file is part of OpenWebSoccer-Sim.
    *
    * OpenWebSoccer-Sim is free software: you can redistribute it
    * and/or modify it under the terms of the
    * GNU Lesser General Public License
    * as published by the Free Software Foundation, either version 3 of
    * the License, or any later version.
    *
    * OpenWebSoccer-Sim is distributed in the hope that it will be
    * useful, but WITHOUT ANY WARRANTY; without even the implied
    * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    * See the GNU Lesser General Public License for more details.
    *
    * You should have received a copy of the GNU Lesser General Public
    * License along with OpenWebSoccer-Sim.
    * If not, see
    <http://www.gnu.org/licenses/>.
-->

<module version="OpenWebsoccer">
    <settings>
        <setting id="googleplus_enable_login" category="social" type="boolean" default="0"/>
        <setting id="googleplus_appname" category="social" type="text" default=""/>
        <setting id="googleplus_clientid" category="social" type="text" default=""/>
        <setting id="googleplus_clientsecret" category="social" type="text" default=""/>
        <setting id="googleplus_developerkey" category="social" type="text" default=""/>
        <setting id="googleplus_enable_likebutton" category="social" type="boolean" default="0"/>
    </settings>

    <blocks>
        <block
                id="googleplus-login-sidebar"
                template="googleplusloginbox"
                model="GoogleplusLoginModel"
                includepages="all"
                area="sidebar"
                weight="1"
                role="guest"/>
        <block
                id="googleplus-like"
                template="googleplus_like"
                includepages="home,news-details,match,todaysmatches,highscore,freeclubs"
                area="content_bottom"
                weight="5"
                role="guest,user"/>
    </blocks>

    <actions>
        <action id="googleplus-login" controller="GoogleplusLoginController" role="guest"/>
    </actions>
</module>

=== teamchef/OpenWebsoccer/addons_old/facebook/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../openwebsoccer.dtd">

<!---
    * This file is part of OpenWebSoccer-Sim.
    *
    * OpenWebSoccer-Sim is free software: you can redistribute it
    * and/or modify it under the terms of the
    * GNU Lesser General Public License
    * as published by the Free Software Foundation, either version 3 of
    * the License, or any later version.
    *
    * OpenWebSoccer-Sim is distributed in the hope that it will be
    * useful, but WITHOUT ANY WARRANTY; without even the implied
    * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    * See the GNU Lesser General Public License for more details.
    *
    * You should have received a copy of the GNU Lesser General Public
    * License along with OpenWebSoccer-Sim.
    * If not, see
    <http://www.gnu.org/licenses/>.
-->

<module version="OpenWebsoccer">
    <settings>
        <setting id="facebook_enable_login" category="social" type="boolean" default="0"/>
        <setting id="facebook_appid" category="social" type="text" default=""/>
        <setting id="facebook_appsecret" category="social" type="text" default=""/>
        <setting id="facebook_enable_comments" category="social" type="boolean" default="0"/>
        <setting id="facebook_enable_likebutton" category="social" type="boolean" default="0"/>
    </settings>

    <blocks>
        <block
                id="facebook-login-sidebar"
                template="facebookloginbox"
                model="FacebookLoginModel"
                includepages="all"
                area="sidebar"
                weight="1"
                role="guest"/>
        <block
                id="facebook-like"
                template="facebook_like"
                includepages="home,news-details,match,todaysmatches,highscore,freeclubs"
                area="content_bottom"
                weight="5"
                role="guest,user"/>
        <block
                id="facebook-sdk"
                template="facebook_sdk"
                includepages="all"
                area="content_top"
                weight="0"
                role="guest,user"/>
        <block
                id="facebook-comments"
                template="facebook_comments"
                includepages="news-details,match"
                area="content_bottom"
                weight="10"
                role="guest,user"/>
    </blocks>

    <actions>
        <action id="facebook-login" controller="FacebookLoginController" role="guest,user">
            <param id="error" type="text" required="false"/>
        </action>

        <action id="facebook-logout" controller="FacebookLogoutController" role="user,guest"/>
    </actions>
</module>

=== teamchef/OpenWebsoccer/addons_old/facebook/adminmessages_de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../openwebsoccer.dtd">

<!---
    * This file is part of OpenWebSoccer-Sim.
    *
    * OpenWebSoccer-Sim is free software: you can redistribute it
    * and/or modify it under the terms of the
    * GNU Lesser General Public License
    * as published by the Free Software Foundation, either version 3 of
    * the License, or any later version.
    *
    * OpenWebSoccer-Sim is distributed in the hope that it will be
    * useful, but WITHOUT ANY WARRANTY; without even the implied
    * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    * See the GNU Lesser General Public License for more details.
    *
    * You should have received a copy of the GNU Lesser General Public
    * License along with OpenWebSoccer-Sim.
    * If not, see
    <http://www.gnu.org/licenses/>.
-->

<module version="OpenWebsoccer">
    <messages>
        <message id="settings_label_facebook_enable_login">Log-In über Facebook aktivieren. Erfordert die Eingabe einer
            APP-ID und des Facebook-Sicherheitscodes (siehe unten). Ausserdem muss die PHP-Erweiterung CURL auf dem
            Server aktiviert sein.
        </message>
        <message id="settings_label_facebook_appid">Facebook App ID</message>
        <message id="settings_label_facebook_appid_help">Erhalten Sie, wenn Sie Ihre Webseite<a
                href="https://developers.facebook.com/apps" target="_blank">als App auf Facebook registrieren</a>.
        </message>
        <message id="settings_label_facebook_appsecret">Facebook App Secret</message>
        <message id="settings_label_facebook_appsecret_help">Erhalten Sie ebenfalls bei der Registrierung Ihrer Webseite
            auf Facebook.
        </message>
        <message id="settings_label_facebook_enable_comments">Diskussionen (z.B. in News und Spielberichten) über ein
            Facebook-Plugin erlauben. Erfordert die Eingabe einer Facebook App ID (siehe oben).
        </message>
        <message id="settings_label_facebook_enable_likebutton">Zeige auf bestimmten Seiten den Facebook-Like-Button
            an.
        </message>
    </messages>
</module>

=== teamchef/OpenWebsoccer/addons_old/premiummicropayment/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../openwebsoccer.dtd">

<!---
    * This file is part of OpenWebSoccer-Sim.
    *
    * OpenWebSoccer-Sim is free software: you can redistribute it
    * and/or modify it under the terms of the
    * GNU Lesser General Public License
    * as published by the Free Software Foundation, either version 3 of
    * the License, or any later version.
    *
    * OpenWebSoccer-Sim is distributed in the hope that it will be
    * useful, but WITHOUT ANY WARRANTY; without even the implied
    * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    * See the GNU Lesser General Public License for more details.
    *
    * You should have received a copy of the GNU Lesser General Public
    * License along with OpenWebSoccer-Sim.
    * If not, see
    <http://www.gnu.org/licenses/>.
-->

<module version="OpenWebsoccer">
    <settings>
        <setting id="micropayment_enabled" category="premium" type="boolean" default="false"/>
        <setting id="micropayment_project" category="premium" type="text" default=""/>
        <setting id="micropayment_accesskey" category="premium" type="text" default=""/>
        <setting id="micropayment_call2pay_enabled" category="premium" type="boolean" default="false"/>
        <setting id="micropayment_handypay_enabled" category="premium" type="boolean" default="false"/>
        <setting id="micropayment_ebank2pay_enabled" category="premium" type="boolean" default="false"/>
        <setting id="micropayment_creditcard_enabled" category="premium" type="boolean" default="false"/>
    </settings>

    <actions>
        <action id="micropayment-redirect" controller="MicropaymentRedirectController" role="user">
            <param id="amount" type="number" required="true"/>
        </action>
    </actions>

    <blocks>
        <block
                id="micropaymentlink"
                template="micropaymentlink"
                includepages="premium-feature-requested"
                area="content_bottom"
                weight="1"
                role="user"/>
    </blocks>
</module>
